### ISSUE TITLE
Error Clodius aggregate: RuntimeError: Invalid interval bounds!

### ISSUE THREAD

**Issue by samuelCollombet** [hms-dbmi/clodius#18]
Hi ,
I am trying to aggregate a bigWig and clidus send me the following error:
```
position: 167772161 progress: 0.05 elapsed: 106.55 remaining: 1885.81
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 167772160
Traceback (most recent call last):
  File "/home/samuel/programs/bin/clodius", line 11, in <module>
    load_entry_point('clodius==0.7.0', 'console_scripts', 'clodius')()
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/clodius/cli/aggregate.py", line 1104, in bigwig
  File "build/bdist.linux-x86_64/egg/clodius/cli/aggregate.py", line 669, in _bigwig
RuntimeError: Invalid interval bounds!
```
(he is still on chr1).
Do you have any idea what it could be? My bigwig seems fine with other programs...
Thanks!

**Comment by Javkhaa** [comment]
I had that issue too, I think you need to specify chromosome size and ordering. 
--chromsizes-filename TEXT  A file containing chromosome sizes and order
I added this and it worked for me
