### ISSUE TITLE
clodius aggregate: NameError: global name '_bigwig' is not defined

### ISSUE THREAD

**Issue by dvera** [hms-dbmi/clodius#28]
On ubuntu xenial with a fresh python 2.7.12 install, I get the following:

```bash
root@609c5b8e4115:/$ clodius aggregate bigwig HistonH3_cre_trt_rep1.bw
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/local/bin/clodius", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clodius/cli/aggregate.py", line 1347, in bigwig
    _bigwig(
NameError: global name '_bigwig' is not defined
```

**Comment by Rmulet** [comment]
I have the same issue. I even tried to use the docker in case it was some OS- or python-related issue, but I get the same error. Any ideas?

**Comment by dvera** [comment]
It worked for me when running it in the higlass container (which has it installed).

**Comment by Rmulet** [comment]
Thanks for the suggestion, but I got the same error. Perhaps we are using different versions of higlass.

**Comment by Rmulet** [comment]
That worked, thanks! Still, I hope they address this issue, as it seems it's being carried over to recent versions of Higlass as well...

**Comment by nvictus** [comment]
Btw, there's no need to aggregate bigwigs anymore. HiGlass can ingest them natively now (`--filetype bigwig --datatype vector`).

**Comment by Rmulet** [comment]
That's great news! Very nice feature, thanks!

**Comment by zhanyinx** [comment]
Hi,
I had the same problem and I tried to upload directly bigwig files, however the coordinates were all shifted from chromosome two on (I am using mm9 mouse build). 

The way I generate the bigwig file is the following:
I have a Grange object containing coordinates and score. I sort the grange object based on seqlevel so that chr2 is immediately after chr1. I export the grange to bigwig using export from rtracklayer

Do you have any idea on how I can solve the shift problem?

Thanks
Zhan

**Comment by nvictus** [comment]
There's a chromosome ordering bug at the moment related to non-primary scaffolds (random and Un contigs). If that's the problem, a workaround for now is to omit the non-primary scaffolds from your bigwig. The second option is to export bedGraph and use clodius.

@pkerpedjiev Looks like clodius's bigwig option was removed in a655ff6 but the command wasn't deprecated.
